# Generated by Django 3.2.7 on 2021-10-04 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Города'},
        ),
        migrations.RenameField(
            model_name='city',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='lon',
            new_name='longitude',
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=3)),
                ('datetime', models.DateTimeField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='api.city')),
            ],
            options={
                'verbose_name_plural': 'Погода',
                'ordering': ['-datetime'],
            },
        ),
        migrations.AddConstraint(
            model_name='weather',
            constraint=models.UniqueConstraint(fields=('datetime', 'city'), name='unique_weather_obj'),
        ),
    ]
