# Generated by Django 3.2.7 on 2021-10-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211005_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='id_api_weatherbit',
            field=models.PositiveIntegerField(default=200000),
            preserve_default=False,
        ),
    ]
