# Generated by Django 3.2.7 on 2021-10-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_city_id_api_weatherbit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='id_api_weatherbit',
            new_name='id_in_openweathermap',
        ),
        migrations.AddField(
            model_name='city',
            name='id_in_weatherbit',
            field=models.PositiveIntegerField(default=100000),
            preserve_default=False,
        ),
    ]
