# Generated by Django 3.2.7 on 2021-10-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211005_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='source',
            field=models.CharField(choices=[('weatherbit', 'weatherbit'), ('openweathermap', 'openweathermap')], default='weatherbit', max_length=30),
            preserve_default=False,
        ),
    ]
